-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.binhluan
(
    id serial NOT NULL,
    maphananh integer NOT NULL,
    cccd_nguoidung character(12) COLLATE pg_catalog."default" NOT NULL,
    noidung text COLLATE pg_catalog."default" NOT NULL,
    thoigian timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    is_hidden boolean DEFAULT false,
    parent_id integer,
    CONSTRAINT binhluan_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.boxchat
(
    maboxchat serial NOT NULL,
    maphananh integer,
    cccd_canbo character(12) COLLATE pg_catalog."default",
    cccd_nguoidan character(12) COLLATE pg_catalog."default",
    CONSTRAINT boxchat_pkey PRIMARY KEY (maboxchat),
    CONSTRAINT boxchat_maphananh_key UNIQUE (maphananh)
);

COMMENT ON TABLE public.boxchat
    IS 'Mỗi phản ánh có 1 box chat riêng giữa người dân và cán bộ.';

CREATE TABLE IF NOT EXISTS public.diachi
(
    madiachi serial NOT NULL,
    tinh character varying(50) COLLATE pg_catalog."default",
    xaphuong character varying(50) COLLATE pg_catalog."default",
    chitiet character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT diachi_pkey PRIMARY KEY (madiachi)
);

CREATE TABLE IF NOT EXISTS public.diachinguoidung
(
    madiachi integer NOT NULL,
    cccd character(12) COLLATE pg_catalog."default" NOT NULL,
    loaidiachi character varying(20) COLLATE pg_catalog."default" NOT NULL,
    thoidiemxacnhan date,
    thoidiemketthuc date,
    CONSTRAINT diachinguoidung_pkey PRIMARY KEY (madiachi, cccd, loaidiachi)
);

COMMENT ON TABLE public.diachinguoidung
    IS 'Xác định loại địa chỉ (cư trú, tạm trú, nơi làm việc) của từng người.';

CREATE TABLE IF NOT EXISTS public.hokhau
(
    mahokhau serial NOT NULL,
    madiachi integer,
    ngaycap date DEFAULT CURRENT_DATE,
    ghichu text COLLATE pg_catalog."default",
    CONSTRAINT hokhau_pkey PRIMARY KEY (mahokhau)
);

COMMENT ON TABLE public.hokhau
    IS 'Lưu thông tin hộ khẩu, gắn với một địa chỉ cư trú.';

CREATE TABLE IF NOT EXISTS public.lichsuthaydoichuho
(
    malichsu serial NOT NULL,
    mahokhau integer NOT NULL,
    cccd_cu character(12) COLLATE pg_catalog."default",
    cccd_moi character(12) COLLATE pg_catalog."default" NOT NULL,
    ngaythaydoi date DEFAULT CURRENT_DATE,
    lydothaydoi character varying(100) COLLATE pg_catalog."default",
    noidung text COLLATE pg_catalog."default",
    nguoithuchien character(12) COLLATE pg_catalog."default",
    CONSTRAINT lichsuthaydoichuho_pkey PRIMARY KEY (malichsu)
);

COMMENT ON TABLE public.lichsuthaydoichuho
    IS 'Lưu lịch sử thay đổi chủ hộ';

CREATE TABLE IF NOT EXISTS public.like_post
(
    maphananh integer NOT NULL,
    cccd character(12) COLLATE pg_catalog."default" NOT NULL,
    thoigian timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT like_post_pkey PRIMARY KEY (maphananh, cccd)
);

CREATE TABLE IF NOT EXISTS public.nguoidung
(
    cccd character(12) COLLATE pg_catalog."default" NOT NULL,
    name character varying(50) COLLATE pg_catalog."default",
    sdt character varying(15) COLLATE pg_catalog."default",
    ngaysinh date,
    gioitinh character varying(10) COLLATE pg_catalog."default",
    dantoc character varying(30) COLLATE pg_catalog."default",
    vaitro character varying(20) COLLATE pg_catalog."default",
    user_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    matkhau character varying(255) COLLATE pg_catalog."default" NOT NULL,
    baomatthongtin boolean DEFAULT true,
    nghenghiep character varying(100) COLLATE pg_catalog."default",
    noilamviec character varying(255) COLLATE pg_catalog."default",
    avatar_url text COLLATE pg_catalog."default" DEFAULT 'image/default_avatar.png'::text,
    CONSTRAINT nguoidung_pkey PRIMARY KEY (cccd),
    CONSTRAINT nguoidung_user_name_key UNIQUE (user_name)
);

COMMENT ON TABLE public.nguoidung
    IS 'Lưu thông tin người dùng (người dân, cán bộ).';

COMMENT ON COLUMN public.nguoidung.baomatthongtin
    IS 'Ẩn thông tin người dân cho đến khi cán bộ xử lý phản ánh.';

CREATE TABLE IF NOT EXISTS public.phananh
(
    maphananh serial NOT NULL,
    cccd character(12) COLLATE pg_catalog."default",
    madiachi integer,
    loaiphananh character varying(100) COLLATE pg_catalog."default",
    trangthaiphananh character varying(50) COLLATE pg_catalog."default" DEFAULT 'ChuaXuLy'::character varying,
    mota text COLLATE pg_catalog."default",
    matepdinhkem integer,
    tieude character varying(255) COLLATE pg_catalog."default",
    is_public boolean DEFAULT false,
    allow_comment boolean DEFAULT true,
    like_count integer DEFAULT 0,
    comment_count integer DEFAULT 0,
    view_count integer DEFAULT 0,
    mavande integer,
    thoigiantao timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    thoigianxuly timestamp without time zone,
    CONSTRAINT phananh_pkey PRIMARY KEY (maphananh)
);

COMMENT ON TABLE public.phananh
    IS 'Lưu thông tin phản ánh của người dân.';

COMMENT ON COLUMN public.phananh.mavande
    IS 'Mã vấn đề mà phản ánh này thuộc về (FK -> vande.mavande)';

COMMENT ON COLUMN public.phananh.thoigiantao
    IS 'Thời điểm tạo phản ánh';

COMMENT ON COLUMN public.phananh.thoigianxuly
    IS 'Thời điểm xử lý/cập nhật trạng thái';

CREATE TABLE IF NOT EXISTS public.tepdinhkem
(
    matepdinhkem serial NOT NULL,
    duongdan text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT tepdinhkem_pkey PRIMARY KEY (matepdinhkem)
);

CREATE TABLE IF NOT EXISTS public.thanhvienhokhau
(
    mahokhau integer NOT NULL,
    cccd character(12) COLLATE pg_catalog."default" NOT NULL,
    quanhechuho character varying(50) COLLATE pg_catalog."default",
    ngaybatdau date DEFAULT CURRENT_DATE,
    ngayketthuc date,
    lydochuyen character varying(100) COLLATE pg_catalog."default",
    noichuyenden text COLLATE pg_catalog."default",
    ghichu text COLLATE pg_catalog."default",
    CONSTRAINT thanhvienhokhau_pkey PRIMARY KEY (mahokhau, cccd)
);

COMMENT ON TABLE public.thanhvienhokhau
    IS 'Liên kết người dân với hộ khẩu và quan hệ với chủ hộ.';

COMMENT ON COLUMN public.thanhvienhokhau.quanhechuho
    IS 'Quan hệ của thành viên với chủ hộ.';

COMMENT ON COLUMN public.thanhvienhokhau.lydochuyen
    IS 'Lý do kết thúc sinh sống tại hộ: Chuyển đi, Qua đời, Tách hộ, v.v.';

COMMENT ON COLUMN public.thanhvienhokhau.noichuyenden
    IS 'Địa chỉ nơi chuyển đến (nếu có)';

COMMENT ON COLUMN public.thanhvienhokhau.ghichu
    IS 'Ghi chú thêm về biến động nhân khẩu';

CREATE TABLE IF NOT EXISTS public.thongbao
(
    mathongbao serial NOT NULL,
    tieude character varying(255) COLLATE pg_catalog."default" NOT NULL,
    noidung text COLLATE pg_catalog."default" NOT NULL,
    matepdinhkem integer,
    nguoidang character(12) COLLATE pg_catalog."default",
    thoigiandang timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    trangthai character varying(20) COLLATE pg_catalog."default" DEFAULT 'HienThi'::character varying,
    CONSTRAINT thongbao_pkey PRIMARY KEY (mathongbao)
);

COMMENT ON TABLE public.thongbao
    IS 'Lưu thông báo do cán bộ hoặc quản lý đăng lên trang chủ hệ thống.';

COMMENT ON COLUMN public.thongbao.matepdinhkem
    IS 'Tệp đính kèm đi kèm thông báo (nếu có).';

CREATE TABLE IF NOT EXISTS public.thongbao_nguoidung
(
    mathongbao_nguoidung serial NOT NULL,
    cccd character(12) COLLATE pg_catalog."default" NOT NULL,
    mathongbao integer,
    noidung text COLLATE pg_catalog."default" NOT NULL,
    loai character varying(50) COLLATE pg_catalog."default" DEFAULT 'General'::character varying,
    trangthai_doc boolean DEFAULT false,
    thoigian timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    mavande integer,
    maphananh integer,
    CONSTRAINT thongbao_nguoidung_pkey PRIMARY KEY (mathongbao_nguoidung)
);

COMMENT ON TABLE public.thongbao_nguoidung
    IS 'Lưu thông báo cá nhân cho từng người dùng với trạng thái đã đọc';

COMMENT ON COLUMN public.thongbao_nguoidung.mathongbao_nguoidung
    IS 'Mã thông báo người dùng (Primary Key)';

COMMENT ON COLUMN public.thongbao_nguoidung.cccd
    IS 'CCCD người nhận thông báo';

COMMENT ON COLUMN public.thongbao_nguoidung.mathongbao
    IS 'Mã thông báo chung (nếu liên kết từ bảng thongbao)';

COMMENT ON COLUMN public.thongbao_nguoidung.noidung
    IS 'Nội dung thông báo';

COMMENT ON COLUMN public.thongbao_nguoidung.loai
    IS 'Loại: General, PhanAnh, VanDe, Chat, System, LichSu';

COMMENT ON COLUMN public.thongbao_nguoidung.trangthai_doc
    IS 'Trạng thái đã đọc (TRUE/FALSE)';

COMMENT ON COLUMN public.thongbao_nguoidung.thoigian
    IS 'Thời điểm tạo thông báo';

COMMENT ON COLUMN public.thongbao_nguoidung.mavande
    IS 'Liên kết đến vấn đề (nếu thông báo về vấn đề)';

COMMENT ON COLUMN public.thongbao_nguoidung.maphananh
    IS 'Liên kết đến phản ánh (nếu thông báo về phản ánh)';

CREATE TABLE IF NOT EXISTS public.tinnhan
(
    tinnhanid serial NOT NULL,
    maboxchat integer,
    nguoigui character(12) COLLATE pg_catalog."default",
    noidung text COLLATE pg_catalog."default" NOT NULL,
    thoigiangui timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    dadoc boolean DEFAULT false,
    matepdinhkem integer,
    CONSTRAINT tinnhan_pkey PRIMARY KEY (tinnhanid)
);

COMMENT ON TABLE public.tinnhan
    IS 'Lưu tin nhắn giữa người dân và cán bộ trong từng box chat.';

CREATE TABLE IF NOT EXISTS public.vande
(
    mavande serial NOT NULL,
    tenvande character varying(255) COLLATE pg_catalog."default" NOT NULL,
    phanloai character varying(100) COLLATE pg_catalog."default" DEFAULT 'Khac'::character varying,
    trangthai character varying(50) COLLATE pg_catalog."default" DEFAULT 'Moi'::character varying,
    ketqua text COLLATE pg_catalog."default",
    ngaytao timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    ngaycapnhat timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    cccd_canbo_xuly character(12) COLLATE pg_catalog."default",
    CONSTRAINT vande_pkey PRIMARY KEY (mavande)
);

COMMENT ON TABLE public.vande
    IS 'Lưu thông tin vấn đề/sự việc được tổng hợp từ nhiều phản ánh của người dân';

COMMENT ON COLUMN public.vande.mavande
    IS 'Mã vấn đề (Primary Key)';

COMMENT ON COLUMN public.vande.tenvande
    IS 'Tên vấn đề (VD: Mất nước khu vực 7, Đường bị hỏng...)';

COMMENT ON COLUMN public.vande.phanloai
    IS 'Phân loại: HaTang, MoiTruong, AnNinh, GiaoThong, YTe, GiaoDuc, VanHoa, Khac';

COMMENT ON COLUMN public.vande.trangthai
    IS 'Trạng thái: Moi, DangXuLy, DaGiaiQuyet, KhongGiaiQuyet';

COMMENT ON COLUMN public.vande.ketqua
    IS 'Kết quả giải quyết vấn đề';

COMMENT ON COLUMN public.vande.ngaytao
    IS 'Thời điểm tạo vấn đề';

COMMENT ON COLUMN public.vande.ngaycapnhat
    IS 'Thời điểm cập nhật cuối cùng';

COMMENT ON COLUMN public.vande.cccd_canbo_xuly
    IS 'CCCD cán bộ được phân công xử lý';

ALTER TABLE IF EXISTS public.binhluan
    ADD CONSTRAINT binhluan_maphananh_fkey FOREIGN KEY (maphananh)
    REFERENCES public.phananh (maphananh) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.binhluan
    ADD CONSTRAINT binhluan_nguoidung_fkey FOREIGN KEY (cccd_nguoidung)
    REFERENCES public.nguoidung (cccd) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.boxchat
    ADD CONSTRAINT boxchat_cccd_canbo_fkey FOREIGN KEY (cccd_canbo)
    REFERENCES public.nguoidung (cccd) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_boxchat_canbo
    ON public.boxchat(cccd_canbo);


ALTER TABLE IF EXISTS public.boxchat
    ADD CONSTRAINT boxchat_cccd_nguoidan_fkey FOREIGN KEY (cccd_nguoidan)
    REFERENCES public.nguoidung (cccd) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_boxchat_nguoidan
    ON public.boxchat(cccd_nguoidan);


ALTER TABLE IF EXISTS public.boxchat
    ADD CONSTRAINT boxchat_maphananh_fkey FOREIGN KEY (maphananh)
    REFERENCES public.phananh (maphananh) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS boxchat_maphananh_key
    ON public.boxchat(maphananh);


ALTER TABLE IF EXISTS public.diachinguoidung
    ADD CONSTRAINT diachinguoidung_cccd_fkey FOREIGN KEY (cccd)
    REFERENCES public.nguoidung (cccd) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_diachinguoidung_cccd
    ON public.diachinguoidung(cccd);


ALTER TABLE IF EXISTS public.diachinguoidung
    ADD CONSTRAINT diachinguoidung_madiachi_fkey FOREIGN KEY (madiachi)
    REFERENCES public.diachi (madiachi) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_diachinguoidung_madiadi
    ON public.diachinguoidung(madiachi);


ALTER TABLE IF EXISTS public.hokhau
    ADD CONSTRAINT hokhau_madiachi_fkey FOREIGN KEY (madiachi)
    REFERENCES public.diachi (madiachi) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_hokhau_madiadi
    ON public.hokhau(madiachi);


ALTER TABLE IF EXISTS public.lichsuthaydoichuho
    ADD CONSTRAINT fk_lichsuthaydoichuho_chuho_cu FOREIGN KEY (cccd_cu)
    REFERENCES public.nguoidung (cccd) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.lichsuthaydoichuho
    ADD CONSTRAINT fk_lichsuthaydoichuho_chuho_moi FOREIGN KEY (cccd_moi)
    REFERENCES public.nguoidung (cccd) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.lichsuthaydoichuho
    ADD CONSTRAINT fk_lichsuthaydoichuho_hokhau FOREIGN KEY (mahokhau)
    REFERENCES public.hokhau (mahokhau) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_lichsuthaydoichuho_mahokhau
    ON public.lichsuthaydoichuho(mahokhau);


ALTER TABLE IF EXISTS public.lichsuthaydoichuho
    ADD CONSTRAINT fk_lichsuthaydoichuho_nguoithuchien FOREIGN KEY (nguoithuchien)
    REFERENCES public.nguoidung (cccd) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.like_post
    ADD CONSTRAINT likepost_nguoidung_fkey FOREIGN KEY (cccd)
    REFERENCES public.nguoidung (cccd) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_like_post_cccd
    ON public.like_post(cccd);


ALTER TABLE IF EXISTS public.like_post
    ADD CONSTRAINT likepost_phananh_fkey FOREIGN KEY (maphananh)
    REFERENCES public.phananh (maphananh) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.phananh
    ADD CONSTRAINT phananh_cccd_fkey FOREIGN KEY (cccd)
    REFERENCES public.nguoidung (cccd) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_phananh_cccd
    ON public.phananh(cccd);


ALTER TABLE IF EXISTS public.phananh
    ADD CONSTRAINT phananh_madiachi_fkey FOREIGN KEY (madiachi)
    REFERENCES public.diachi (madiachi) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_phananh_madiadi
    ON public.phananh(madiachi);


ALTER TABLE IF EXISTS public.phananh
    ADD CONSTRAINT phananh_matepdinhkem_fkey FOREIGN KEY (matepdinhkem)
    REFERENCES public.tepdinhkem (matepdinhkem) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.phananh
    ADD CONSTRAINT phananh_mavande_fkey FOREIGN KEY (mavande)
    REFERENCES public.vande (mavande) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_phananh_mavande
    ON public.phananh(mavande);


ALTER TABLE IF EXISTS public.thanhvienhokhau
    ADD CONSTRAINT thanhvienhokhau_cccd_fkey FOREIGN KEY (cccd)
    REFERENCES public.nguoidung (cccd) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_thanhvienhokhau_cccd
    ON public.thanhvienhokhau(cccd);


ALTER TABLE IF EXISTS public.thanhvienhokhau
    ADD CONSTRAINT thanhvienhokhau_mahokhau_fkey FOREIGN KEY (mahokhau)
    REFERENCES public.hokhau (mahokhau) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_thanhvienhokhau_mahokhau
    ON public.thanhvienhokhau(mahokhau);


ALTER TABLE IF EXISTS public.thongbao
    ADD CONSTRAINT thongbao_matepdinhkem_fkey FOREIGN KEY (matepdinhkem)
    REFERENCES public.tepdinhkem (matepdinhkem) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.thongbao
    ADD CONSTRAINT thongbao_nguoidang_fkey FOREIGN KEY (nguoidang)
    REFERENCES public.nguoidung (cccd) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.thongbao_nguoidung
    ADD CONSTRAINT thongbao_nguoidung_cccd_fkey FOREIGN KEY (cccd)
    REFERENCES public.nguoidung (cccd) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.thongbao_nguoidung
    ADD CONSTRAINT thongbao_nguoidung_maphananh_fkey FOREIGN KEY (maphananh)
    REFERENCES public.phananh (maphananh) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_thongbao_nguoidung_maphananh
    ON public.thongbao_nguoidung(maphananh);


ALTER TABLE IF EXISTS public.thongbao_nguoidung
    ADD CONSTRAINT thongbao_nguoidung_mathongbao_fkey FOREIGN KEY (mathongbao)
    REFERENCES public.thongbao (mathongbao) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.thongbao_nguoidung
    ADD CONSTRAINT thongbao_nguoidung_mavande_fkey FOREIGN KEY (mavande)
    REFERENCES public.vande (mavande) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_thongbao_nguoidung_mavande
    ON public.thongbao_nguoidung(mavande);


ALTER TABLE IF EXISTS public.tinnhan
    ADD CONSTRAINT tinnhan_maboxchat_fkey FOREIGN KEY (maboxchat)
    REFERENCES public.boxchat (maboxchat) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_tinnhan_maboxchat
    ON public.tinnhan(maboxchat);


ALTER TABLE IF EXISTS public.tinnhan
    ADD CONSTRAINT tinnhan_matepdinhkem_fkey FOREIGN KEY (matepdinhkem)
    REFERENCES public.tepdinhkem (matepdinhkem) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.tinnhan
    ADD CONSTRAINT tinnhan_nguoigui_fkey FOREIGN KEY (nguoigui)
    REFERENCES public.nguoidung (cccd) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.vande
    ADD CONSTRAINT vande_cccd_canbo_fkey FOREIGN KEY (cccd_canbo_xuly)
    REFERENCES public.nguoidung (cccd) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_vande_canbo
    ON public.vande(cccd_canbo_xuly);

END;