-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.boxchat
(
    maboxchat serial NOT NULL,
    maphananh integer,
    cccd_canbo character(12) COLLATE pg_catalog."default",
    cccd_nguoidan character(12) COLLATE pg_catalog."default",
    CONSTRAINT boxchat_pkey PRIMARY KEY (maboxchat),
    CONSTRAINT boxchat_maphananh_key UNIQUE (maphananh)
);

COMMENT ON TABLE public.boxchat
    IS 'Mỗi phản ánh có 1 box chat riêng giữa người dân và cán bộ.';

CREATE TABLE IF NOT EXISTS public.diachi
(
    madiachi serial NOT NULL,
    tinh character varying(50) COLLATE pg_catalog."default",
    xaphuong character varying(50) COLLATE pg_catalog."default",
    chitiet character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT diachi_pkey PRIMARY KEY (madiachi)
);

CREATE TABLE IF NOT EXISTS public.diachinguoidung
(
    madiachi integer NOT NULL,
    cccd character(12) COLLATE pg_catalog."default" NOT NULL,
    loaidiachi character varying(20) COLLATE pg_catalog."default" NOT NULL,
    thoidiemxacnhan date,
    thoidiemketthuc date,
    CONSTRAINT diachinguoidung_pkey PRIMARY KEY (madiachi, cccd, loaidiachi)
);

COMMENT ON TABLE public.diachinguoidung
    IS 'Xác định loại địa chỉ (cư trú, tạm trú, nơi làm việc) của từng người.';

CREATE TABLE IF NOT EXISTS public.hokhau
(
    mahokhau serial NOT NULL,
    madiachi integer,
    ngaycap date DEFAULT CURRENT_DATE,
    ghichu text COLLATE pg_catalog."default",
    CONSTRAINT hokhau_pkey PRIMARY KEY (mahokhau)
);

COMMENT ON TABLE public.hokhau
    IS 'Lưu thông tin hộ khẩu, gắn với một địa chỉ cư trú.';

CREATE TABLE IF NOT EXISTS public.nguoidung
(
    cccd character(12) COLLATE pg_catalog."default" NOT NULL,
    name character varying(50) COLLATE pg_catalog."default",
    sdt character varying(15) COLLATE pg_catalog."default",
    ngaysinh date,
    gioitinh character varying(10) COLLATE pg_catalog."default",
    dantoc character varying(30) COLLATE pg_catalog."default",
    vaitro character varying(20) COLLATE pg_catalog."default",
    user_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    matkhau character varying(255) COLLATE pg_catalog."default" NOT NULL,
    baomatthongtin boolean DEFAULT true,
    CONSTRAINT nguoidung_pkey PRIMARY KEY (cccd),
    CONSTRAINT nguoidung_user_name_key UNIQUE (user_name)
);

COMMENT ON TABLE public.nguoidung
    IS 'Lưu thông tin người dùng (người dân, cán bộ).';

COMMENT ON COLUMN public.nguoidung.baomatthongtin
    IS 'Ẩn thông tin người dân cho đến khi cán bộ xử lý phản ánh.';

CREATE TABLE IF NOT EXISTS public.phananh
(
    maphananh serial NOT NULL,
    cccd character(12) COLLATE pg_catalog."default",
    madiachi integer,
    loaiphananh character varying(100) COLLATE pg_catalog."default",
    trangthaiphananh character varying(50) COLLATE pg_catalog."default" DEFAULT 'ChuaXuLy'::character varying,
    mota text COLLATE pg_catalog."default",
    matepdinhkem integer,
    CONSTRAINT phananh_pkey PRIMARY KEY (maphananh)
);

COMMENT ON TABLE public.phananh
    IS 'Lưu thông tin phản ánh của người dân.';

CREATE TABLE IF NOT EXISTS public.tepdinhkem
(
    matepdinhkem serial NOT NULL,
    duongdan text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT tepdinhkem_pkey PRIMARY KEY (matepdinhkem)
);

CREATE TABLE IF NOT EXISTS public.thanhvienhokhau
(
    mahokhau integer NOT NULL,
    cccd character(12) COLLATE pg_catalog."default" NOT NULL,
    quanhechuho character varying(50) COLLATE pg_catalog."default",
    ngaybatdau date DEFAULT CURRENT_DATE,
    ngayketthuc date,
    CONSTRAINT thanhvienhokhau_pkey PRIMARY KEY (mahokhau, cccd)
);

COMMENT ON TABLE public.thanhvienhokhau
    IS 'Liên kết người dân với hộ khẩu và quan hệ với chủ hộ.';

COMMENT ON COLUMN public.thanhvienhokhau.quanhechuho
    IS 'Quan hệ của thành viên với chủ hộ.';

CREATE TABLE IF NOT EXISTS public.thongbao
(
    mathongbao serial NOT NULL,
    tieude character varying(255) COLLATE pg_catalog."default" NOT NULL,
    noidung text COLLATE pg_catalog."default" NOT NULL,
    matepdinhkem integer,
    nguoidang character(12) COLLATE pg_catalog."default",
    thoigiandang timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    trangthai character varying(20) COLLATE pg_catalog."default" DEFAULT 'HienThi'::character varying,
    CONSTRAINT thongbao_pkey PRIMARY KEY (mathongbao)
);

COMMENT ON TABLE public.thongbao
    IS 'Lưu thông báo do cán bộ hoặc quản lý đăng lên trang chủ hệ thống.';

COMMENT ON COLUMN public.thongbao.matepdinhkem
    IS 'Tệp đính kèm đi kèm thông báo (nếu có).';

CREATE TABLE IF NOT EXISTS public.tinnhan
(
    tinnhanid serial NOT NULL,
    maboxchat integer,
    nguoigui character(12) COLLATE pg_catalog."default",
    noidung text COLLATE pg_catalog."default" NOT NULL,
    thoigiangui timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    dadoc boolean DEFAULT false,
    matepdinhkem integer,
    CONSTRAINT tinnhan_pkey PRIMARY KEY (tinnhanid)
);

COMMENT ON TABLE public.tinnhan
    IS 'Lưu tin nhắn giữa người dân và cán bộ trong từng box chat.';

ALTER TABLE IF EXISTS public.boxchat
    ADD CONSTRAINT boxchat_cccd_canbo_fkey FOREIGN KEY (cccd_canbo)
    REFERENCES public.nguoidung (cccd) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.boxchat
    ADD CONSTRAINT boxchat_cccd_nguoidan_fkey FOREIGN KEY (cccd_nguoidan)
    REFERENCES public.nguoidung (cccd) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.boxchat
    ADD CONSTRAINT boxchat_maphananh_fkey FOREIGN KEY (maphananh)
    REFERENCES public.phananh (maphananh) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS boxchat_maphananh_key
    ON public.boxchat(maphananh);


ALTER TABLE IF EXISTS public.diachinguoidung
    ADD CONSTRAINT diachinguoidung_cccd_fkey FOREIGN KEY (cccd)
    REFERENCES public.nguoidung (cccd) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.diachinguoidung
    ADD CONSTRAINT diachinguoidung_madiachi_fkey FOREIGN KEY (madiachi)
    REFERENCES public.diachi (madiachi) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.hokhau
    ADD CONSTRAINT hokhau_madiachi_fkey FOREIGN KEY (madiachi)
    REFERENCES public.diachi (madiachi) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.phananh
    ADD CONSTRAINT phananh_cccd_fkey FOREIGN KEY (cccd)
    REFERENCES public.nguoidung (cccd) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.phananh
    ADD CONSTRAINT phananh_madiachi_fkey FOREIGN KEY (madiachi)
    REFERENCES public.diachi (madiachi) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.phananh
    ADD CONSTRAINT phananh_matepdinhkem_fkey FOREIGN KEY (matepdinhkem)
    REFERENCES public.tepdinhkem (matepdinhkem) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.thanhvienhokhau
    ADD CONSTRAINT thanhvienhokhau_cccd_fkey FOREIGN KEY (cccd)
    REFERENCES public.nguoidung (cccd) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.thanhvienhokhau
    ADD CONSTRAINT thanhvienhokhau_mahokhau_fkey FOREIGN KEY (mahokhau)
    REFERENCES public.hokhau (mahokhau) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.thongbao
    ADD CONSTRAINT thongbao_matepdinhkem_fkey FOREIGN KEY (matepdinhkem)
    REFERENCES public.tepdinhkem (matepdinhkem) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.thongbao
    ADD CONSTRAINT thongbao_nguoidang_fkey FOREIGN KEY (nguoidang)
    REFERENCES public.nguoidung (cccd) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.tinnhan
    ADD CONSTRAINT tinnhan_maboxchat_fkey FOREIGN KEY (maboxchat)
    REFERENCES public.boxchat (maboxchat) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.tinnhan
    ADD CONSTRAINT tinnhan_matepdinhkem_fkey FOREIGN KEY (matepdinhkem)
    REFERENCES public.tepdinhkem (matepdinhkem) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.tinnhan
    ADD CONSTRAINT tinnhan_nguoigui_fkey FOREIGN KEY (nguoigui)
    REFERENCES public.nguoidung (cccd) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;

END;